### ISSUE TITLE
more controls please, such as speed, and storage of random setting

### ISSUE THREAD

**Issue by Shintaro-Miyazaki** [commoningtoys/CowardVSHeroes#1]
more controls please, such as speed, and storage of random setting

**Comment by Yyyyaaaannnnoooo** [comment]
what do you mean by "storage of random setting"

**Comment by Shintaro-Miyazaki** [comment]
It is possible store the setting generated by the random generator, what ever it does. So that you can recreat the same setting afterwards.

**Comment by Yyyyaaaannnnoooo** [comment]
than rather have a slider to choose how many are cowards and how many are heroes
